# Generated by Django 4.2.7 on 2025-09-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=None, help_text='ID único de 6 caracteres para la sala', max_length=10, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Esperando'), ('active', 'Activa'), ('ended', 'Terminada')], default='waiting', help_text='Estado actual de la sala', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo de la sala (opcional)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la sala')),
                ('started_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando la sala se volvió activa', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fecha y hora cuando la sala terminó', null=True)),
                ('max_participants', models.IntegerField(default=10, help_text='Número máximo de participantes permitidos')),
                ('translation_enabled', models.BooleanField(default=True, help_text='Si la traducción de señas está habilitada')),
                ('stt_enabled', models.BooleanField(default=True, help_text='Si el speech-to-text está habilitado')),
                ('tts_enabled', models.BooleanField(default=True, help_text='Si el text-to-speech está habilitado')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único de sesión para este participante', max_length=50, unique=True)),
                ('name', models.CharField(default='Participante', help_text='Nombre que muestra el participante', max_length=50)),
                ('is_connected', models.BooleanField(default=True, help_text='Si el participante está actualmente conectado')),
                ('has_camera', models.BooleanField(default=True, help_text='Si el participante tiene cámara habilitada')),
                ('has_microphone', models.BooleanField(default=True, help_text='Si el participante tiene micrófono habilitado')),
                ('is_deaf', models.BooleanField(default=False, help_text='Si el participante es sordo (necesita traducción visual)')),
                ('is_mute', models.BooleanField(default=False, help_text='Si el participante es mudo (necesita traducción de señas)')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se unió el participante')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Cuándo se desconectó el participante', null=True)),
                ('room', models.ForeignKey(help_text='Sala a la que pertenece este participante', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'unique_together': {('room', 'session_id')},
            },
        ),
    ]
