# Generated by Django 4.2.7 on 2025-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('group', 'Conversación Grupal'), ('quick', 'Conversación Rápida')], default='group', help_text='Tipo de sala: grupal o rápida', max_length=20),
        ),
    ]
